import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { Link } from 'react-router-dom';
import { Menu, X } from 'lucide-react';
import { useState } from 'react';
import { useAuthStore } from '@/store/auth';
export default function Navbar() {
    const [isOpen, setIsOpen] = useState(false);
    const { user, logout } = useAuthStore();
    return (_jsxs("nav", { className: "bg-surface border-b border-border", children: [_jsx("div", { className: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8", children: _jsxs("div", { className: "flex justify-between items-center h-16", children: [_jsxs(Link, { to: "/", className: "flex items-center space-x-2", children: [_jsx("div", { className: "w-8 h-8 bg-gradient-to-r from-primary to-accent rounded-lg" }), _jsx("span", { className: "text-xl font-bold text-text", children: "Comp" })] }), _jsxs("div", { className: "hidden md:flex items-center space-x-8", children: [_jsx(Link, { to: "/events", className: "text-muted hover:text-text transition", children: "Events" }), _jsx(Link, { to: "/projects", className: "text-muted hover:text-text transition", children: "Projects" }), user ? (_jsxs(_Fragment, { children: [_jsx(Link, { to: "/dashboard", className: "text-muted hover:text-text transition", children: "Dashboard" }), (user.role === 'ADMIN' || user.role === 'SUPER_ADMIN') && (_jsx(Link, { to: "/admin", className: "text-accent hover:text-primary transition", children: "Admin" })), _jsx("button", { onClick: logout, className: "px-4 py-2 bg-primary text-surface rounded-lg hover:bg-primary/80 transition", children: "Logout" })] })) : (_jsxs(_Fragment, { children: [_jsx(Link, { to: "/login", className: "text-muted hover:text-text transition", children: "Login" }), _jsx(Link, { to: "/register", className: "px-4 py-2 bg-primary text-surface rounded-lg hover:bg-primary/80 transition", children: "Register" })] }))] }), _jsx("button", { onClick: () => setIsOpen(!isOpen), className: "md:hidden text-muted hover:text-text", children: isOpen ? _jsx(X, { size: 24 }) : _jsx(Menu, { size: 24 }) })] }) }), isOpen && (_jsx("div", { className: "md:hidden bg-card border-t border-border", children: _jsxs("div", { className: "px-4 pt-4 pb-4 space-y-4", children: [_jsx(Link, { to: "/events", className: "block text-muted hover:text-text transition", children: "Events" }), _jsx(Link, { to: "/projects", className: "block text-muted hover:text-text transition", children: "Projects" }), user ? (_jsxs(_Fragment, { children: [_jsx(Link, { to: "/dashboard", className: "block text-muted hover:text-text transition", children: "Dashboard" }), (user.role === 'ADMIN' || user.role === 'SUPER_ADMIN') && (_jsx(Link, { to: "/admin", className: "block text-accent hover:text-primary transition", children: "Admin" })), _jsx("button", { onClick: () => {
                                        logout();
                                        setIsOpen(false);
                                    }, className: "w-full px-4 py-2 bg-primary text-surface rounded-lg hover:bg-primary/80 transition", children: "Logout" })] })) : (_jsxs(_Fragment, { children: [_jsx(Link, { to: "/login", className: "block text-muted hover:text-text transition", children: "Login" }), _jsx(Link, { to: "/register", className: "block w-full px-4 py-2 bg-primary text-surface rounded-lg hover:bg-primary/80 transition text-center", children: "Register" })] }))] }) }))] }));
}
