"""phase_2_initial_schema

Revision ID: 7f344338c966
Revises: 
Create Date: 2026-09-04 14:09:58.785352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7f344338c966'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_sponsors',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('logo_url', sa.String(length=2048), nullable=True),
    sa.Column('website_url', sa.String(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_sponsors_event_id'), 'event_sponsors', ['event_id'], unique=False)
    op.create_table('profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=2048), nullable=True),
    sa.Column('college', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('bio', sa.String(length=1000), nullable=True),
    sa.Column('skills', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('projects',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('problem', sa.Text(), nullable=True),
    sa.Column('solution', sa.Text(), nullable=True),
    sa.Column('tech_stack', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('github_url', sa.String(length=2048), nullable=True),
    sa.Column('demo_url', sa.String(length=2048), nullable=True),
    sa.Column('video_url', sa.String(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_projects_event_id', 'projects', ['event_id'], unique=False)
    op.create_index('ix_projects_team_id', 'projects', ['team_id'], unique=False)
    op.drop_index('ix_leaderboard_event_id', table_name='leaderboard')
    op.drop_table('leaderboard')
    op.add_column('audit_logs', sa.Column('event_type', sa.String(length=100), nullable=False))
    op.alter_column('audit_logs', 'action',
               existing_type=postgresql.ENUM('LOGIN_SUCCESS', 'LOGIN_FAILED', 'LOGOUT', 'PASSWORD_CHANGED', 'USER_CREATED', 'USER_UPDATED', 'USER_SUSPENDED', 'EVENT_CREATED', 'EVENT_UPDATED', 'EVENT_PUBLISHED', 'EVENT_DELETED', 'REGISTRATION_CREATED', 'REGISTRATION_CANCELLED', 'TEAM_CREATED', 'TEAM_UPDATED', 'PROJECT_SUBMITTED', 'PROJECT_UPDATED', 'CERTIFICATE_GENERATED', 'ADMIN_ROLE_CHANGED', 'DATA_EXPORTED', 'DATA_DELETED', name='auditaction'),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('audit_logs', 'ip_address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('audit_logs', 'endpoint',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('audit_logs', 'http_method',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_index('idx_audit_logs_user_date', table_name='audit_logs')
    op.create_index('ix_audit_logs_event_type', 'audit_logs', ['event_type'], unique=False)
    op.create_index('ix_audit_logs_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.drop_constraint('audit_logs_user_id_fkey', 'audit_logs', type_='foreignkey')
    op.create_foreign_key(None, 'audit_logs', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_column('audit_logs', 'details')
    op.add_column('badges', sa.Column('icon', sa.String(length=2048), nullable=False))
    op.alter_column('badges', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               nullable=False)
    op.alter_column('badges', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_column('badges', 'icon_url')
    op.add_column('certificates', sa.Column('certificate_type', sa.Enum('PARTICIPATION', 'WINNER', 'RUNNER_UP', 'FINALIST', 'SPECIAL_RECOGNITION', name='certificatetype'), nullable=False))
    op.add_column('certificates', sa.Column('certificate_code', sa.String(length=100), nullable=False))
    op.add_column('certificates', sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('certificates', sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_index('ix_certificates_verification_code', table_name='certificates')
    op.create_index(op.f('ix_certificates_certificate_code'), 'certificates', ['certificate_code'], unique=True)
    op.create_index('ix_certificates_event_id', 'certificates', ['event_id'], unique=False)
    op.drop_constraint('certificates_event_id_fkey', 'certificates', type_='foreignkey')
    op.drop_constraint('certificates_user_id_fkey', 'certificates', type_='foreignkey')
    op.create_foreign_key(None, 'certificates', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'certificates', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('certificates', 'achievement')
    op.drop_column('certificates', 'verification_code')
    op.drop_column('certificates', 'certificate_url')
    op.drop_column('certificates', 'created_at')
    op.drop_column('certificates', 'issued_date')
    op.drop_column('certificates', 'title')
    op.add_column('evaluations', sa.Column('uiux_score', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('evaluations', sa.Column('feedback', sa.Text(), nullable=True))
    op.alter_column('evaluations', 'innovation_score',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('evaluations', 'technical_score',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('evaluations', 'impact_score',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('evaluations', 'presentation_score',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('evaluations', 'total_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('evaluations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('evaluations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_index('ix_evaluations_judge_id', 'evaluations', ['judge_id'], unique=False)
    op.create_index('ix_evaluations_submission_id', 'evaluations', ['submission_id'], unique=False)
    op.create_unique_constraint('uq_evaluations_submission_judge', 'evaluations', ['submission_id', 'judge_id'])
    op.drop_constraint('evaluations_submission_id_fkey', 'evaluations', type_='foreignkey')
    op.drop_constraint('evaluations_judge_id_fkey', 'evaluations', type_='foreignkey')
    op.create_foreign_key(None, 'evaluations', 'submissions', ['submission_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'evaluations', 'judges', ['judge_id'], ['id'], ondelete='CASCADE')
    op.drop_column('evaluations', 'ui_ux_score')
    op.drop_column('evaluations', 'comments')
    op.add_column('events', sa.Column('slug', sa.String(length=255), nullable=False))
    op.add_column('events', sa.Column('team_size_min', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('team_size_max', sa.Integer(), nullable=True))
    op.alter_column('events', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('events', 'start_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True)
    op.alter_column('events', 'end_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True)
    op.alter_column('events', 'registration_deadline',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True)
    op.alter_column('events', 'prize_pool',
               existing_type=sa.VARCHAR(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
    op.alter_column('events', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('events', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_index('ix_events_event_type', 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_slug'), 'events', ['slug'], unique=True)
    op.create_index('ix_events_start_date', 'events', ['start_date'], unique=False)
    op.create_index('ix_events_status', 'events', ['status'], unique=False)
    op.drop_constraint('events_created_by_fkey', 'events', type_='foreignkey')
    op.drop_column('events', 'created_by')
    op.drop_column('events', 'participant_count')
    op.drop_column('events', 'is_published')
    op.drop_column('events', 'category')
    op.add_column('judges', sa.Column('name', sa.String(length=255), nullable=False))
    op.add_column('judges', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('judges', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('judges', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_unique_constraint(None, 'judges', ['user_id'])
    op.drop_constraint('judges_event_id_fkey', 'judges', type_='foreignkey')
    op.drop_constraint('judges_user_id_fkey', 'judges', type_='foreignkey')
    op.create_foreign_key(None, 'judges', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('judges', 'event_id')
    op.drop_column('judges', 'assigned_at')
    op.add_column('login_attempts', sa.Column('failure_reason', sa.String(length=255), nullable=True))
    op.alter_column('login_attempts', 'ip_address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('login_attempts', 'success',
               existing_type=sa.VARCHAR(),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('login_attempts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_index('ix_login_attempts_email', 'login_attempts', ['email'], unique=False)
    op.create_index('ix_login_attempts_user_id', 'login_attempts', ['user_id'], unique=False)
    op.drop_constraint('login_attempts_user_id_fkey', 'login_attempts', type_='foreignkey')
    op.create_foreign_key(None, 'login_attempts', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.alter_column('notifications', 'message',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('notifications', 'type',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('EVENT_ANNOUNCEMENT', 'REGISTRATION_CONFIRMED', 'REGISTRATION_CANCELLED', 'TEAM_INVITE', 'SUBMISSION_UPDATE', 'EVALUATION_COMPLETE', 'CERTIFICATE_ISSUED', 'BADGE_AWARDED', 'GENERAL', name='notificationtype'),
               existing_nullable=False)
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_index('ix_notifications_created_at', 'notifications', ['created_at'], unique=False)
    op.create_index('ix_notifications_is_read', 'notifications', ['is_read'], unique=False)
    op.create_index('ix_notifications_user_id', 'notifications', ['user_id'], unique=False)
    op.drop_constraint('notifications_user_id_fkey', 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('notifications', 'resource_type')
    op.drop_column('notifications', 'read_at')
    op.drop_column('notifications', 'resource_id')
    op.add_column('registrations', sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_index('idx_registrations_event_user', table_name='registrations')
    op.create_index('ix_registrations_status', 'registrations', ['status'], unique=False)
    op.create_unique_constraint('uq_registrations_user_event', 'registrations', ['user_id', 'event_id'])
    op.drop_constraint('registrations_event_id_fkey', 'registrations', type_='foreignkey')
    op.drop_constraint('registrations_user_id_fkey', 'registrations', type_='foreignkey')
    op.create_foreign_key(None, 'registrations', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'registrations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('registrations', 'created_at')
    op.drop_column('registrations', 'updated_at')
    op.add_column('security_alerts', sa.Column('type', sa.String(length=100), nullable=False))
    op.add_column('security_alerts', sa.Column('status', sa.Enum('OPEN', 'INVESTIGATING', 'RESOLVED', 'DISMISSED', name='securityalertstatus'), nullable=False))
    op.add_column('security_alerts', sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('security_alerts', 'severity',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='securityalertseverity'),
               existing_nullable=False)
    op.alter_column('security_alerts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_index('ix_security_alerts_created_at', 'security_alerts', ['created_at'], unique=False)
    op.create_index('ix_security_alerts_severity', 'security_alerts', ['severity'], unique=False)
    op.create_index('ix_security_alerts_status', 'security_alerts', ['status'], unique=False)
    op.create_index('ix_security_alerts_user_id', 'security_alerts', ['user_id'], unique=False)
    op.drop_constraint('security_alerts_user_id_fkey', 'security_alerts', type_='foreignkey')
    op.create_foreign_key(None, 'security_alerts', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_column('security_alerts', 'alert_type')
    op.drop_column('security_alerts', 'resolved')
    op.add_column('submissions', sa.Column('project_id', sa.UUID(), nullable=False))
    op.alter_column('submissions', 'submitted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('submissions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_index('ix_submissions_project_id', 'submissions', ['project_id'], unique=False)
    op.create_index('ix_submissions_status', 'submissions', ['status'], unique=False)
    op.drop_constraint('submissions_user_id_fkey', 'submissions', type_='foreignkey')
    op.drop_constraint('submissions_team_id_fkey', 'submissions', type_='foreignkey')
    op.drop_constraint('submissions_event_id_fkey', 'submissions', type_='foreignkey')
    op.create_foreign_key(None, 'submissions', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'submissions', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    op.drop_column('submissions', 'demo_url')
    op.drop_column('submissions', 'description')
    op.drop_column('submissions', 'problem_statement')
    op.drop_column('submissions', 'tech_stack')
    op.drop_column('submissions', 'project_title')
    op.drop_column('submissions', 'screenshots_urls')
    op.drop_column('submissions', 'user_id')
    op.drop_column('submissions', 'presentation_url')
    op.drop_column('submissions', 'team_id')
    op.drop_column('submissions', 'video_url')
    op.drop_column('submissions', 'created_at')
    op.drop_column('submissions', 'solution')
    op.drop_column('submissions', 'github_url')
    op.add_column('team_members', sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('team_members', 'role',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('LEADER', 'MEMBER', name='teammemberrole'),
               existing_nullable=False)
    op.drop_index('idx_team_members_team_user', table_name='team_members')
    op.drop_index('ix_team_members_team_id', table_name='team_members')
    op.drop_constraint('team_members_user_id_fkey', 'team_members', type_='foreignkey')
    op.drop_constraint('team_members_team_id_fkey', 'team_members', type_='foreignkey')
    op.create_foreign_key(None, 'team_members', 'teams', ['team_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'team_members', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('team_members', 'created_at')
    op.drop_column('team_members', 'id')
    op.add_column('teams', sa.Column('leader_id', sa.UUID(), nullable=False))
    op.alter_column('teams', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('teams', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_index('ix_teams_leader_id', 'teams', ['leader_id'], unique=False)
    op.drop_constraint('teams_event_id_fkey', 'teams', type_='foreignkey')
    op.drop_constraint('teams_created_by_fkey', 'teams', type_='foreignkey')
    op.create_foreign_key(None, 'teams', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'teams', 'users', ['leader_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('teams', 'created_by')
    op.drop_column('teams', 'description')
    op.alter_column('user_badges', 'awarded_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_index('idx_user_badges', table_name='user_badges')
    op.create_index('ix_user_badges_user_id', 'user_badges', ['user_id'], unique=False)
    op.drop_constraint('user_badges_user_id_fkey', 'user_badges', type_='foreignkey')
    op.drop_constraint('user_badges_badge_id_fkey', 'user_badges', type_='foreignkey')
    op.create_foreign_key(None, 'user_badges', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_badges', 'badges', ['badge_id'], ['id'], ondelete='CASCADE')
    op.drop_column('user_badges', 'id')
    op.add_column('user_sessions', sa.Column('session_hash', sa.String(length=255), nullable=False))
    op.add_column('user_sessions', sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_sessions', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('user_sessions', sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('user_sessions', 'ip_address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_index('ix_user_sessions_expires_at', 'user_sessions', ['expires_at'], unique=False)
    op.create_index('ix_user_sessions_session_hash', 'user_sessions', ['session_hash'], unique=False)
    op.create_index('ix_user_sessions_user_id', 'user_sessions', ['user_id'], unique=False)
    op.create_unique_constraint(None, 'user_sessions', ['session_hash'])
    op.drop_constraint('user_sessions_user_id_fkey', 'user_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'user_sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('user_sessions', 'last_activity')
    op.drop_column('user_sessions', 'device_info')
    op.add_column('users', sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'DELETED', name='accountstatus'), nullable=False))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.create_index('ix_users_status', 'users', ['status'], unique=False)
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'name')
    op.drop_column('users', 'college')
    op.drop_column('users', 'xp_points')
    op.drop_column('users', 'profile_photo_url')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'skills')
    op.drop_column('users', 'year')
    op.drop_column('users', 'department')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('department', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('skills', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('bio', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('profile_photo_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('xp_points', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('college', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_index('ix_users_status', table_name='users')
    op.drop_index('ix_users_role', table_name='users')
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('users', 'status')
    op.add_column('user_sessions', sa.Column('device_info', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user_sessions', sa.Column('last_activity', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_sessions', type_='foreignkey')
    op.create_foreign_key('user_sessions_user_id_fkey', 'user_sessions', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'user_sessions', type_='unique')
    op.drop_index('ix_user_sessions_user_id', table_name='user_sessions')
    op.drop_index('ix_user_sessions_session_hash', table_name='user_sessions')
    op.drop_index('ix_user_sessions_expires_at', table_name='user_sessions')
    op.alter_column('user_sessions', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('user_sessions', 'ip_address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('user_sessions', 'revoked_at')
    op.drop_column('user_sessions', 'expires_at')
    op.drop_column('user_sessions', 'last_seen')
    op.drop_column('user_sessions', 'session_hash')
    op.add_column('user_badges', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_badges', type_='foreignkey')
    op.drop_constraint(None, 'user_badges', type_='foreignkey')
    op.create_foreign_key('user_badges_badge_id_fkey', 'user_badges', 'badges', ['badge_id'], ['id'])
    op.create_foreign_key('user_badges_user_id_fkey', 'user_badges', 'users', ['user_id'], ['id'])
    op.drop_index('ix_user_badges_user_id', table_name='user_badges')
    op.create_index('idx_user_badges', 'user_badges', ['user_id', 'badge_id'], unique=True)
    op.alter_column('user_badges', 'awarded_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.add_column('teams', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('teams', sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.create_foreign_key('teams_created_by_fkey', 'teams', 'users', ['created_by'], ['id'])
    op.create_foreign_key('teams_event_id_fkey', 'teams', 'events', ['event_id'], ['id'])
    op.drop_index('ix_teams_leader_id', table_name='teams')
    op.alter_column('teams', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('teams', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('teams', 'leader_id')
    op.add_column('team_members', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('team_members', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'team_members', type_='foreignkey')
    op.drop_constraint(None, 'team_members', type_='foreignkey')
    op.create_foreign_key('team_members_team_id_fkey', 'team_members', 'teams', ['team_id'], ['id'])
    op.create_foreign_key('team_members_user_id_fkey', 'team_members', 'users', ['user_id'], ['id'])
    op.create_index('ix_team_members_team_id', 'team_members', ['team_id'], unique=False)
    op.create_index('idx_team_members_team_user', 'team_members', ['team_id', 'user_id'], unique=True)
    op.alter_column('team_members', 'role',
               existing_type=sa.Enum('LEADER', 'MEMBER', name='teammemberrole'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('team_members', 'joined_at')
    op.add_column('submissions', sa.Column('github_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('submissions', sa.Column('solution', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('submissions', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('submissions', sa.Column('video_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('submissions', sa.Column('team_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('submissions', sa.Column('presentation_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('submissions', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('submissions', sa.Column('screenshots_urls', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('submissions', sa.Column('project_title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('submissions', sa.Column('tech_stack', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('submissions', sa.Column('problem_statement', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('submissions', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('submissions', sa.Column('demo_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'submissions', type_='foreignkey')
    op.drop_constraint(None, 'submissions', type_='foreignkey')
    op.create_foreign_key('submissions_event_id_fkey', 'submissions', 'events', ['event_id'], ['id'])
    op.create_foreign_key('submissions_team_id_fkey', 'submissions', 'teams', ['team_id'], ['id'])
    op.create_foreign_key('submissions_user_id_fkey', 'submissions', 'users', ['user_id'], ['id'])
    op.drop_index('ix_submissions_status', table_name='submissions')
    op.drop_index('ix_submissions_project_id', table_name='submissions')
    op.alter_column('submissions', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('submissions', 'submitted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('submissions', 'project_id')
    op.add_column('security_alerts', sa.Column('resolved', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('security_alerts', sa.Column('alert_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'security_alerts', type_='foreignkey')
    op.create_foreign_key('security_alerts_user_id_fkey', 'security_alerts', 'users', ['user_id'], ['id'])
    op.drop_index('ix_security_alerts_user_id', table_name='security_alerts')
    op.drop_index('ix_security_alerts_status', table_name='security_alerts')
    op.drop_index('ix_security_alerts_severity', table_name='security_alerts')
    op.drop_index('ix_security_alerts_created_at', table_name='security_alerts')
    op.alter_column('security_alerts', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('security_alerts', 'severity',
               existing_type=sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='securityalertseverity'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('security_alerts', 'resolved_at')
    op.drop_column('security_alerts', 'status')
    op.drop_column('security_alerts', 'type')
    op.add_column('registrations', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('registrations', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'registrations', type_='foreignkey')
    op.drop_constraint(None, 'registrations', type_='foreignkey')
    op.create_foreign_key('registrations_user_id_fkey', 'registrations', 'users', ['user_id'], ['id'])
    op.create_foreign_key('registrations_event_id_fkey', 'registrations', 'events', ['event_id'], ['id'])
    op.drop_constraint('uq_registrations_user_event', 'registrations', type_='unique')
    op.drop_index('ix_registrations_status', table_name='registrations')
    op.create_index('idx_registrations_event_user', 'registrations', ['event_id', 'user_id'], unique=True)
    op.drop_column('registrations', 'registered_at')
    op.add_column('notifications', sa.Column('resource_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('read_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('resource_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key('notifications_user_id_fkey', 'notifications', 'users', ['user_id'], ['id'])
    op.drop_index('ix_notifications_user_id', table_name='notifications')
    op.drop_index('ix_notifications_is_read', table_name='notifications')
    op.drop_index('ix_notifications_created_at', table_name='notifications')
    op.alter_column('notifications', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('notifications', 'type',
               existing_type=sa.Enum('EVENT_ANNOUNCEMENT', 'REGISTRATION_CONFIRMED', 'REGISTRATION_CANCELLED', 'TEAM_INVITE', 'SUBMISSION_UPDATE', 'EVALUATION_COMPLETE', 'CERTIFICATE_ISSUED', 'BADGE_AWARDED', 'GENERAL', name='notificationtype'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('notifications', 'message',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_constraint(None, 'login_attempts', type_='foreignkey')
    op.create_foreign_key('login_attempts_user_id_fkey', 'login_attempts', 'users', ['user_id'], ['id'])
    op.drop_index('ix_login_attempts_user_id', table_name='login_attempts')
    op.drop_index('ix_login_attempts_email', table_name='login_attempts')
    op.alter_column('login_attempts', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('login_attempts', 'success',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('login_attempts', 'ip_address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('login_attempts', 'failure_reason')
    op.add_column('judges', sa.Column('assigned_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('judges', sa.Column('event_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'judges', type_='foreignkey')
    op.create_foreign_key('judges_user_id_fkey', 'judges', 'users', ['user_id'], ['id'])
    op.create_foreign_key('judges_event_id_fkey', 'judges', 'events', ['event_id'], ['id'])
    op.drop_constraint(None, 'judges', type_='unique')
    op.alter_column('judges', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('judges', 'updated_at')
    op.drop_column('judges', 'bio')
    op.drop_column('judges', 'name')
    op.add_column('events', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('events', sa.Column('is_published', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('events', sa.Column('participant_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('events', sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('events_created_by_fkey', 'events', 'users', ['created_by'], ['id'])
    op.drop_index('ix_events_status', table_name='events')
    op.drop_index('ix_events_start_date', table_name='events')
    op.drop_index(op.f('ix_events_slug'), table_name='events')
    op.drop_index('ix_events_event_type', table_name='events')
    op.alter_column('events', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('events', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('events', 'prize_pool',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('events', 'registration_deadline',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('events', 'end_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('events', 'start_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('events', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('events', 'team_size_max')
    op.drop_column('events', 'team_size_min')
    op.drop_column('events', 'slug')
    op.add_column('evaluations', sa.Column('comments', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('evaluations', sa.Column('ui_ux_score', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'evaluations', type_='foreignkey')
    op.drop_constraint(None, 'evaluations', type_='foreignkey')
    op.create_foreign_key('evaluations_judge_id_fkey', 'evaluations', 'judges', ['judge_id'], ['id'])
    op.create_foreign_key('evaluations_submission_id_fkey', 'evaluations', 'submissions', ['submission_id'], ['id'])
    op.drop_constraint('uq_evaluations_submission_judge', 'evaluations', type_='unique')
    op.drop_index('ix_evaluations_submission_id', table_name='evaluations')
    op.drop_index('ix_evaluations_judge_id', table_name='evaluations')
    op.alter_column('evaluations', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('evaluations', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('evaluations', 'total_score',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('evaluations', 'presentation_score',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('evaluations', 'impact_score',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('evaluations', 'technical_score',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('evaluations', 'innovation_score',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('evaluations', 'feedback')
    op.drop_column('evaluations', 'uiux_score')
    op.add_column('certificates', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('certificates', sa.Column('issued_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('certificates', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('certificates', sa.Column('certificate_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('certificates', sa.Column('verification_code', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('certificates', sa.Column('achievement', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'certificates', type_='foreignkey')
    op.drop_constraint(None, 'certificates', type_='foreignkey')
    op.create_foreign_key('certificates_user_id_fkey', 'certificates', 'users', ['user_id'], ['id'])
    op.create_foreign_key('certificates_event_id_fkey', 'certificates', 'events', ['event_id'], ['id'])
    op.drop_index('ix_certificates_event_id', table_name='certificates')
    op.drop_index(op.f('ix_certificates_certificate_code'), table_name='certificates')
    op.create_index('ix_certificates_verification_code', 'certificates', ['verification_code'], unique=True)
    op.drop_column('certificates', 'extra_data')
    op.drop_column('certificates', 'issued_at')
    op.drop_column('certificates', 'certificate_code')
    op.drop_column('certificates', 'certificate_type')
    op.add_column('badges', sa.Column('icon_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('badges', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('badges', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               nullable=True)
    op.drop_column('badges', 'icon')
    op.add_column('audit_logs', sa.Column('details', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.create_foreign_key('audit_logs_user_id_fkey', 'audit_logs', 'users', ['user_id'], ['id'])
    op.drop_index('ix_audit_logs_resource', table_name='audit_logs')
    op.drop_index('ix_audit_logs_event_type', table_name='audit_logs')
    op.create_index('idx_audit_logs_user_date', 'audit_logs', ['user_id', 'created_at'], unique=False)
    op.alter_column('audit_logs', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('audit_logs', 'http_method',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('audit_logs', 'endpoint',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('audit_logs', 'ip_address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('audit_logs', 'action',
               existing_type=sa.String(length=255),
               type_=postgresql.ENUM('LOGIN_SUCCESS', 'LOGIN_FAILED', 'LOGOUT', 'PASSWORD_CHANGED', 'USER_CREATED', 'USER_UPDATED', 'USER_SUSPENDED', 'EVENT_CREATED', 'EVENT_UPDATED', 'EVENT_PUBLISHED', 'EVENT_DELETED', 'REGISTRATION_CREATED', 'REGISTRATION_CANCELLED', 'TEAM_CREATED', 'TEAM_UPDATED', 'PROJECT_SUBMITTED', 'PROJECT_UPDATED', 'CERTIFICATE_GENERATED', 'ADMIN_ROLE_CHANGED', 'DATA_EXPORTED', 'DATA_DELETED', name='auditaction'),
               existing_nullable=False)
    op.drop_column('audit_logs', 'event_type')
    op.create_table('leaderboard',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('event_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('team_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('submission_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('rank', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name='leaderboard_event_id_fkey'),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], name='leaderboard_submission_id_fkey'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name='leaderboard_team_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='leaderboard_pkey')
    )
    op.create_index('ix_leaderboard_event_id', 'leaderboard', ['event_id'], unique=False)
    op.drop_index('ix_projects_team_id', table_name='projects')
    op.drop_index('ix_projects_event_id', table_name='projects')
    op.drop_table('projects')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_event_sponsors_event_id'), table_name='event_sponsors')
    op.drop_table('event_sponsors')
    # ### end Alembic commands ###
