import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
export default function AdminDashboard() {
    return (_jsxs("div", { className: "p-8", children: [_jsxs("div", { className: "flex justify-between items-start mb-8", children: [_jsxs("div", { children: [_jsx("h1", { className: "text-3xl font-bold text-text", children: "Admin Dashboard" }), _jsx("p", { className: "text-muted mt-2", children: "Real-time platform overview" })] }), _jsxs("div", { className: "flex items-center gap-2 px-4 py-2 bg-danger/20 text-danger rounded-lg", children: [_jsx("div", { className: "w-2 h-2 bg-danger rounded-full animate-pulse" }), _jsx("span", { className: "font-medium", children: "LIVE" })] })] }), _jsx("div", { className: "grid grid-cols-1 md:grid-cols-4 gap-4 mb-8", children: [
                    { label: 'Total Students', value: '1,234', icon: '👥' },
                    { label: 'Active Events', value: '12', icon: '📅' },
                    { label: 'Registrations', value: '5,678', icon: '✓' },
                    { label: 'Submissions', value: '342', icon: '📤' },
                ].map((stat, i) => (_jsxs("div", { className: "bg-card rounded-lg border border-border p-6", children: [_jsx("div", { className: "text-3xl mb-2", children: stat.icon }), _jsx("p", { className: "text-muted text-sm mb-2", children: stat.label }), _jsx("p", { className: "text-2xl font-bold text-text", children: stat.value })] }, i))) }), _jsxs("div", { className: "grid grid-cols-1 lg:grid-cols-3 gap-6", children: [_jsxs("div", { className: "lg:col-span-2 bg-card rounded-lg border border-border p-6", children: [_jsx("h2", { className: "text-xl font-bold text-text mb-4", children: "Registration Trend" }), _jsx("div", { className: "h-64 bg-surface rounded-lg flex items-center justify-center text-muted", children: "Chart Placeholder" })] }), _jsxs("div", { className: "bg-card rounded-lg border border-border p-6", children: [_jsx("h2", { className: "text-xl font-bold text-text mb-4", children: "Recent Activity" }), _jsx("div", { className: "space-y-3", children: [1, 2, 3, 4].map((i) => (_jsxs("div", { className: "text-sm border-b border-border pb-3 last:border-b-0", children: [_jsxs("p", { className: "text-text font-medium", children: ["User registered for Event ", i] }), _jsx("p", { className: "text-muted text-xs", children: "2 minutes ago" })] }, i))) })] })] })] }));
}
